[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "heavy-machinery-predictive-maintenance"
version = "0.1.0"
dependencies = []

[project.scripts]
train-model = "src.ml.train:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]